//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int EntryId { get; set; }
        public string UserEntryId { get; set; }
        public int MetalType { get; set; }
        public string PlaceOfPurchase { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public decimal AmountOfPurchase { get; set; }
    
        public virtual Metal Metal { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
